spring.application.name: nckh_motel-room_be
server:
  port: ${PORT}
spring:
  datasource:
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      #spring.servlet.multipart.location=D:/temp
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
jwt:
  key: ${JWT_KEY}
idea:
  max:
    intellisense:
      filesize: 2500